import type { MorningstarRow, ModelUniverseRow, ModelId } from "./types"

// ─── Morningstar reference data (sample — replace with real Excel upload) ─────
export const SAMPLE_MORNINGSTAR: MorningstarRow[] = [
  // US Equity
  { ticker: "VTI",  name: "Vanguard Total Stock Market ETF",   msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "VOO",  name: "Vanguard S&P 500 ETF",              msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "IVV",  name: "iShares Core S&P 500 ETF",          msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "SPY",  name: "SPDR S&P 500 ETF Trust",            msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "QQQ",  name: "Invesco QQQ Trust",                  msStyle: "Large Growth", assetClass: "US Equity",    region: "US",              factors: ["Growth", "Momentum"] },
  { ticker: "VUG",  name: "Vanguard Growth ETF",                msStyle: "Large Growth", assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "VTV",  name: "Vanguard Value ETF",                 msStyle: "Large Value",  assetClass: "US Equity",    region: "US",              factors: ["Value"] },
  { ticker: "IWM",  name: "iShares Russell 2000 ETF",           msStyle: "Small Blend",  assetClass: "US Equity",    region: "US",              factors: ["Size"] },
  { ticker: "IJR",  name: "iShares Core S&P Small-Cap ETF",     msStyle: "Small Blend",  assetClass: "US Equity",    region: "US",              factors: ["Size"] },
  { ticker: "VBR",  name: "Vanguard Small-Cap Value ETF",       msStyle: "Small Value",  assetClass: "US Equity",    region: "US",              factors: ["Value","Size"] },
  { ticker: "AVUV", name: "Avantis US Small Cap Value ETF",     msStyle: "Small Value",  assetClass: "US Equity",    region: "US",              factors: ["Value","Size","Profitability"] },
  { ticker: "QUAL", name: "iShares MSCI USA Quality Factor ETF",msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: ["Quality"] },
  { ticker: "MTUM", name: "iShares MSCI USA Momentum Factor",   msStyle: "Large Growth", assetClass: "US Equity",    region: "US",              factors: ["Momentum"] },
  { ticker: "USMV", name: "iShares MSCI USA Min Vol Factor ETF",msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: ["Low Volatility"] },
  { ticker: "ESGU", name: "iShares MSCI USA ESG Screened ETF",  msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "ESGV", name: "Vanguard ESG US Stock ETF",          msStyle: "Large Blend",  assetClass: "US Equity",    region: "US",              factors: [] },
  // International Equity
  { ticker: "VXUS", name: "Vanguard Total Intl Stock ETF",      msStyle: "Foreign Large Blend", assetClass: "Intl Equity", region: "Global ex-US",  factors: [],
    splitRegions: [{ region: "Developed ex-US", weight: 0.80 }, { region: "Emerging", weight: 0.20 }] },
  { ticker: "IXUS", name: "iShares Core MSCI Total Intl Stock", msStyle: "Foreign Large Blend", assetClass: "Intl Equity", region: "Global ex-US",  factors: [],
    splitRegions: [{ region: "Developed ex-US", weight: 0.78 }, { region: "Emerging", weight: 0.22 }] },
  { ticker: "IEFA", name: "iShares Core MSCI EAFE ETF",         msStyle: "Foreign Large Blend", assetClass: "Intl Equity", region: "Developed ex-US", factors: [] },
  { ticker: "VEA",  name: "Vanguard FTSE Developed Markets ETF",msStyle: "Foreign Large Blend", assetClass: "Intl Equity", region: "Developed ex-US", factors: [] },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity", region: "Emerging", factors: [] },
  { ticker: "VWO",  name: "Vanguard FTSE Emerging Markets ETF", msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity", region: "Emerging", factors: [] },
  { ticker: "AVDV", name: "Avantis Intl Small Cap Value ETF",   msStyle: "Foreign Large Value", assetClass: "Intl Equity", region: "Developed ex-US", factors: ["Value","Size"] },
  { ticker: "ESGE", name: "iShares MSCI EM ESG Screened ETF",   msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity", region: "Emerging", factors: [] },
  // Fixed Income
  { ticker: "BND",  name: "Vanguard Total Bond Market ETF",     msStyle: "Intermediate Core Bond", assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", msStyle: "Intermediate Core Bond", assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "BNDX", name: "Vanguard Total Intl Bond ETF",       msStyle: "World Bond",             assetClass: "Fixed Income", region: "Global ex-US", factors: [] },
  { ticker: "IAGG", name: "iShares Core Intl Aggregate Bond",   msStyle: "World Bond",             assetClass: "Fixed Income", region: "Global ex-US", factors: [] },
  { ticker: "TIP",  name: "iShares TIPS Bond ETF",              msStyle: "Inflation-Protected Bond", assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "VTIP", name: "Vanguard Short-Term Inflation-Protected Sec", msStyle: "Inflation-Protected Bond", assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "HYG",  name: "iShares iBoxx $ High Yield Corp Bond",msStyle: "High Yield Bond",      assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "JNK",  name: "SPDR Bloomberg High Yield Bond ETF", msStyle: "High Yield Bond",       assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "SHY",  name: "iShares 1-3 Year Treasury Bond ETF", msStyle: "Short-Term Bond",       assetClass: "Fixed Income", region: "US", factors: [] },
  { ticker: "TLT",  name: "iShares 20+ Year Treasury Bond ETF", msStyle: "Long-Term Bond",        assetClass: "Fixed Income", region: "US", factors: [] },
  // Alternatives
  { ticker: "VNQ",  name: "Vanguard Real Estate ETF",           msStyle: "Real Estate",   assetClass: "Real Assets",  region: "US", factors: [] },
  { ticker: "VNQI", name: "Vanguard Global ex-US Real Estate",  msStyle: "Real Estate",   assetClass: "Real Assets",  region: "Global ex-US", factors: [] },
  { ticker: "GSG",  name: "iShares S&P GSCI Commodity ETF",     msStyle: "Commodities",   assetClass: "Real Assets",  region: "Global", factors: [] },
  { ticker: "PDBC", name: "Invesco Optimum Yield Diversified Commodity", msStyle: "Commodities", assetClass: "Real Assets", region: "Global", factors: [] },
]

// ─── Model universe (which tickers belong to each model) ──────────────────────
export const SAMPLE_MODEL_UNIVERSE: ModelUniverseRow[] = [
  // Core Allocation
  { modelId: "core-allocation", ticker: "VOO",  name: "Vanguard S&P 500 ETF",              role: "US Large Cap Core" },
  { modelId: "core-allocation", ticker: "IEFA", name: "iShares Core MSCI EAFE ETF",         role: "Intl Developed" },
  { modelId: "core-allocation", ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", role: "Emerging Markets" },
  { modelId: "core-allocation", ticker: "IJR",  name: "iShares Core S&P Small-Cap ETF",     role: "US Small Cap" },
  { modelId: "core-allocation", ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", role: "US Core Bond" },
  { modelId: "core-allocation", ticker: "IAGG", name: "iShares Core Intl Aggregate Bond",   role: "Intl Bond" },
  { modelId: "core-allocation", ticker: "VNQ",  name: "Vanguard Real Estate ETF",           role: "Real Estate" },
  // Factor Tilt
  { modelId: "factor-tilt", ticker: "AVUV", name: "Avantis US Small Cap Value ETF",     role: "US Small Cap Value" },
  { modelId: "factor-tilt", ticker: "AVDV", name: "Avantis Intl Small Cap Value ETF",   role: "Intl Small Cap Value" },
  { modelId: "factor-tilt", ticker: "QUAL", name: "iShares MSCI USA Quality Factor ETF",role: "US Quality" },
  { modelId: "factor-tilt", ticker: "MTUM", name: "iShares MSCI USA Momentum Factor",   role: "US Momentum" },
  { modelId: "factor-tilt", ticker: "USMV", name: "iShares MSCI USA Min Vol Factor ETF",role: "US Low Vol" },
  { modelId: "factor-tilt", ticker: "VTV",  name: "Vanguard Value ETF",                 role: "US Large Cap Value" },
  { modelId: "factor-tilt", ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", role: "Emerging Markets" },
  { modelId: "factor-tilt", ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", role: "Core Bond" },
  { modelId: "factor-tilt", ticker: "TIP",  name: "iShares TIPS Bond ETF",              role: "Inflation Protection" },
  // ESG / Responsible
  { modelId: "esg-responsible", ticker: "ESGU", name: "iShares MSCI USA ESG Screened ETF",  role: "US Large Cap ESG" },
  { modelId: "esg-responsible", ticker: "ESGV", name: "Vanguard ESG US Stock ETF",          role: "US Broad ESG" },
  { modelId: "esg-responsible", ticker: "ESGE", name: "iShares MSCI EM ESG Screened ETF",   role: "Emerging Markets ESG" },
  { modelId: "esg-responsible", ticker: "IEFA", name: "iShares Core MSCI EAFE ETF",         role: "Intl Developed" },
  { modelId: "esg-responsible", ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", role: "Core Bond" },
  { modelId: "esg-responsible", ticker: "BNDX", name: "Vanguard Total Intl Bond ETF",       role: "Intl Bond" },
  { modelId: "esg-responsible", ticker: "VNQ",  name: "Vanguard Real Estate ETF",           role: "Real Estate" },
  // Active Blend
  { modelId: "active-blend", ticker: "VOO",  name: "Vanguard S&P 500 ETF",              role: "US Large Cap Core (Passive)" },
  { modelId: "active-blend", ticker: "QQQ",  name: "Invesco QQQ Trust",                  role: "US Large Cap Growth (Active-like)" },
  { modelId: "active-blend", ticker: "AVUV", name: "Avantis US Small Cap Value ETF",     role: "US Small Cap (Active)" },
  { modelId: "active-blend", ticker: "AVDV", name: "Avantis Intl Small Cap Value ETF",   role: "Intl (Active)" },
  { modelId: "active-blend", ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", role: "Emerging Markets" },
  { modelId: "active-blend", ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", role: "Core Bond (Passive)" },
  { modelId: "active-blend", ticker: "HYG",  name: "iShares iBoxx $ High Yield Corp Bond",role: "High Yield" },
  { modelId: "active-blend", ticker: "PDBC", name: "Invesco Optimum Yield Diversified Commodity", role: "Commodities" },
  // Institutional Plus
  { modelId: "institutional-plus", ticker: "IVV",  name: "iShares Core S&P 500 ETF",          role: "US Large Cap Core" },
  { modelId: "institutional-plus", ticker: "IEFA", name: "iShares Core MSCI EAFE ETF",         role: "Intl Developed" },
  { modelId: "institutional-plus", ticker: "IEMG", name: "iShares Core MSCI Emerging Markets", role: "Emerging Markets" },
  { modelId: "institutional-plus", ticker: "AVUV", name: "Avantis US Small Cap Value ETF",     role: "US Small Cap Value" },
  { modelId: "institutional-plus", ticker: "AVDV", name: "Avantis Intl Small Cap Value ETF",   role: "Intl Small Cap Value" },
  { modelId: "institutional-plus", ticker: "AGG",  name: "iShares Core US Aggregate Bond ETF", role: "US Core Bond" },
  { modelId: "institutional-plus", ticker: "BNDX", name: "Vanguard Total Intl Bond ETF",       role: "Intl Bond" },
  { modelId: "institutional-plus", ticker: "VTIP", name: "Vanguard Short-Term TIPS",           role: "Inflation Protection" },
  { modelId: "institutional-plus", ticker: "VNQ",  name: "Vanguard Real Estate ETF",           role: "Real Estate" },
  { modelId: "institutional-plus", ticker: "VNQI", name: "Vanguard Global ex-US Real Estate",  role: "Intl Real Estate" },
  { modelId: "institutional-plus", ticker: "GSG",  name: "iShares S&P GSCI Commodity ETF",     role: "Commodities" },
]
