import type { MorningstarRow, ModelUniverseRow } from "./types"

export const SAMPLE_MORNINGSTAR: MorningstarRow[] = [
  { ticker: "VOO",  name: "Vanguard S&P 500 ETF",                      msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "VTV",  name: "Vanguard Value ETF",                         msStyle: "Large Value",               assetClass: "US Equity",    region: "US",              factors: ["Value"] },
  { ticker: "VUG",  name: "Vanguard Growth ETF",                        msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "VB",   name: "Vanguard Small-Cap ETF",                     msStyle: "Small Blend",               assetClass: "US Equity",    region: "US",              factors: ["Size"] },
  { ticker: "RSP",  name: "Invesco S&P 500 Equal Weight ETF",           msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "OEF",  name: "iShares S&P 100 ETF",                        msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "IVV",  name: "iShares Core S&P 500 ETF",                   msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "IVE",  name: "iShares S&P 500 Value ETF",                  msStyle: "Large Value",               assetClass: "US Equity",    region: "US",              factors: ["Value"] },
  { ticker: "IVW",  name: "iShares S&P 500 Growth ETF",                 msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "SCHG", name: "Schwab US Large-Cap Growth ETF",             msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "AVUV", name: "Avantis US Small Cap Value ETF",             msStyle: "Small Value",               assetClass: "US Equity",    region: "US",              factors: ["Value","Size"] },
  { ticker: "ZAP",  name: "Invesco Zacks Multi-Asset Income ETF",       msStyle: "Large Value",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "DYNF", name: "iShares US Equity Factor ETF",               msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Value","Quality","Momentum","Low Volatility"] },
  { ticker: "BLCR", name: "BlackRock US Equity Factor Rotation ETF",    msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Value","Quality","Momentum"] },
  { ticker: "BAI",  name: "BlackRock AI Innovators ETF",                msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "MTUM", name: "iShares MSCI USA Momentum Factor ETF",       msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Momentum"] },
  { ticker: "QUAL", name: "iShares MSCI USA Quality Factor ETF",        msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Quality"] },
  { ticker: "USMV", name: "iShares MSCI USA Min Vol Factor ETF",        msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Low Volatility"] },
  { ticker: "JQUA", name: "JPMorgan US Quality Factor ETF",             msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Quality"] },
  { ticker: "SHLD", name: "Global X S&P 500 Collar 95-110 ETF",         msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "THRO", name: "Pacer US Cash Cows Growth ETF",              msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: ["Quality"] },
  { ticker: "XLK",  name: "Technology Select Sector SPDR Fund",         msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: ["Growth"] },
  { ticker: "XLY",  name: "Consumer Discretionary Select Sector SPDR",  msStyle: "Large Growth",              assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "XLE",  name: "Energy Select Sector SPDR Fund",             msStyle: "Large Value",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "XLV",  name: "Health Care Select Sector SPDR Fund",        msStyle: "Large Blend",               assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "ITA",  name: "iShares US Aerospace & Defense ETF",         msStyle: "Mid Blend",                 assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "IFRA", name: "iShares US Infrastructure ETF",              msStyle: "Mid Blend",                 assetClass: "US Equity",    region: "US",              factors: [] },
  { ticker: "VEA",  name: "Vanguard FTSE Developed Markets ETF",        msStyle: "Foreign Large Blend",       assetClass: "Intl Equity",  region: "Developed ex-US", factors: [] },
  { ticker: "VWO",  name: "Vanguard FTSE Emerging Markets ETF",         msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity",  region: "Emerging",        factors: [] },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets ETF",     msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity",  region: "Emerging",        factors: [] },
  { ticker: "SPEM", name: "SPDR Portfolio Emerging Markets ETF",        msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity",  region: "Emerging",        factors: [] },
  { ticker: "XCEM", name: "Columbia EM Core ex-China ETF",              msStyle: "Diversified Emerging Mkts", assetClass: "Intl Equity",  region: "Emerging",        factors: [] },
  { ticker: "EFG",  name: "iShares MSCI EAFE Growth ETF",               msStyle: "Foreign Large Growth",      assetClass: "Intl Equity",  region: "Developed ex-US", factors: ["Growth"] },
  { ticker: "EFV",  name: "iShares MSCI EAFE Value ETF",                msStyle: "Foreign Large Value",       assetClass: "Intl Equity",  region: "Developed ex-US", factors: ["Value"] },
  { ticker: "IVLU", name: "iShares Edge MSCI Intl Value Factor ETF",    msStyle: "Foreign Large Value",       assetClass: "Intl Equity",  region: "Developed ex-US", factors: ["Value"] },
  { ticker: "IDEF", name: "iShares Edge MSCI Intl Defensive ETF",       msStyle: "Foreign Large Blend",       assetClass: "Intl Equity",  region: "Developed ex-US", factors: ["Low Volatility","Quality"] },
  { ticker: "IAGG", name: "iShares Core Intl Aggregate Bond ETF",       msStyle: "World Bond",                assetClass: "Fixed Income", region: "Global ex-US",    factors: [],
    splitRegions: [{ region: "Developed ex-US", weight: 0.85 }, { region: "Emerging", weight: 0.15 }] },
  { ticker: "BNDX", name: "Vanguard Total Intl Bond ETF",               msStyle: "World Bond",                assetClass: "Fixed Income", region: "Global ex-US",    factors: [] },
  { ticker: "BIV",  name: "Vanguard Intermediate-Term Bond ETF",        msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "BLV",  name: "Vanguard Long-Term Bond ETF",                msStyle: "Long-Term Bond",            assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "BSV",  name: "Vanguard Short-Term Bond ETF",               msStyle: "Short-Term Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "VMBS", name: "Vanguard Mortgage-Backed Securities ETF",    msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "GOVT", name: "iShares US Treasury Bond ETF",               msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "MBB",  name: "iShares MBS ETF",                            msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "IUSB", name: "iShares Core Total USD Bond Market ETF",     msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "ICVT", name: "iShares Convertible Bond ETF",               msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "BINC", name: "BlackRock Flexible Income ETF",              msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "EMB",  name: "iShares J.P. Morgan USD EM Bond ETF",        msStyle: "World Bond",                assetClass: "Fixed Income", region: "Emerging",        factors: [] },
  { ticker: "HYDB", name: "iShares High Yield Bond Factor ETF",         msStyle: "High Yield Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "HYMB", name: "SPDR Nuveen Bloomberg High Yield Muni ETF",  msStyle: "High Yield Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "MUB",  name: "iShares National Muni Bond ETF",             msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "SUB",  name: "iShares Short-Term National Muni Bond ETF",  msStyle: "Short-Term Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "LMUB", name: "Franklin Dynamic Municipal Bond ETF",        msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "CMF",  name: "iShares California Muni Bond ETF",           msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "DFCA", name: "Dimensional California Muni Bond ETF",       msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF",        msStyle: "Short-Term Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "SCHR", name: "Schwab Intermediate-Term US Treasury ETF",   msStyle: "Intermediate Core Bond",    assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "TLH",  name: "iShares 10-20 Year Treasury Bond ETF",       msStyle: "Long-Term Bond",            assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "SPTL", name: "SPDR Portfolio Long Term Treasury ETF",      msStyle: "Long-Term Bond",            assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "VTIP", name: "Vanguard Short-Term Infl-Protected Sec ETF", msStyle: "Inflation-Protected Bond",  assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "STIP", name: "iShares 0-5 Year TIPS Bond ETF",             msStyle: "Inflation-Protected Bond",  assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "TFLO", name: "iShares Treasury Floating Rate Bond ETF",    msStyle: "Short-Term Bond",           assetClass: "Fixed Income", region: "US",              factors: [] },
  { ticker: "BCI",  name: "abrdn Bloomberg All Commodity Strategy ETF", msStyle: "Commodities",               assetClass: "Real Assets",  region: "Global",          factors: [] },
  { ticker: "IAU",  name: "iShares Gold Trust",                         msStyle: "Commodities",               assetClass: "Real Assets",  region: "Global",          factors: [] },
  { ticker: "IAUM", name: "iShares Gold Trust Micro ETF",               msStyle: "Commodities",               assetClass: "Real Assets",  region: "Global",          factors: [] },
]

export const SAMPLE_MODEL_UNIVERSE: ModelUniverseRow[] = [
  ...["BCI","HYDB","IAGG","IAUM","ICVT","IUSB","SGOV","VTIP","AVUV","IEMG","IVLU","RSP","SCHG","SPEM","VOO","XLK","XLY","ZAP"].map(t => ({ modelId: "stp" as const, ticker: t, name: t, role: "" })),
  ...["BCI","HYMB","IAUM","MUB","SGOV","SUB","AVUV","IEMG","IVLU","RSP","SCHG","SPEM","VOO","XLK","XLY","ZAP","HYDB","IAGG","ICVT","IUSB","VTIP","XLV"].map(t => ({ modelId: "stp-tax-aware" as const, ticker: t, name: t, role: "" })),
  ...["EFG","IAU","BINC","GOVT","IAGG","IVLU","JQUA","MTUM","SCHG","SCHR","SHLD","SPEM","TLH","VMBS","VOO","VTV","XCEM","XLK","HYDB","ICVT","EMB","IFRA","SPTL","TFLO","XLE"].map(t => ({ modelId: "savvy-strategic" as const, ticker: t, name: t, role: "" })),
  ...["LMUB","GOVT","IAGG","IAU","IVLU","JQUA","SCHG","VOO","SPEM","EFG","SHLD","VTV","XCEM","XLK","MTUM","CMF","DFCA","HYMB","OEF"].map(t => ({ modelId: "savvy-strategic-tax-aware" as const, ticker: t, name: t, role: "" })),
  ...["GOVT","IAGG","IAU","ICVT","IUSB","MBB","TLH","DYNF","EFV","IEMG","IVE","IVV","IVW","BAI","BLCR","EFG","IDEF","THRO","MTUM","QUAL","ITA","LMUB","MUB","STIP","USMV"].map(t => ({ modelId: "blackrock-target-allocation" as const, ticker: t, name: t, role: "" })),
  ...["BIV","BNDX","BSV","VB","VEA","VMBS","VTV","VUG","VWO"].map(t => ({ modelId: "vanguard-crsp" as const, ticker: t, name: t, role: "" })),
]
